[package]
name = "XY-Model"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile.release]
lto = true

[dependencies]
rustfft = { version = "6.2.0" }
wide = { version = "0.7.32", default-features = false, features = ["std"] }
rand = { version = "0.9.0-beta.1", default-features = false, features = ["std", "std_rng", "os_rng"] }
tokio = { version = "1.42.0", default-features = false, features = ["rt-multi-thread"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio", "migrate", "derive"] }
num-complex = "0.4.6"
