[package]
name = "XY-Model"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
rand = { version = "0.9.0-beta.1", default-features = false, features = ["std", "std_rng", "os_rng"] }
tokio = { version = "1.42.0", default-features = false, features = ["rt-multi-thread"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio", "migrate", "derive"] }